"""Generate the head of the two tables of Nallino, Part II p. 301 (master PDF page 750; Maslama's tables of the signs
of the Arab and of the Persian years and months) as a TikZ picture drawn to the columns of the body of the tables, and
print the @cols line of the page file. Positions were measured on the print (PDF points, 1/72 in): the rules of the
columns, the ink of the texts of the head (whose centres the nodes take) and the baselines of the horizontal Latin
lines; the sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0750-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 64.7  # the outer edge of the left frame rule on the print (pt)
Y0 = 144.5  # the top of the heavy rule over the tables on the print (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "!": 1.0 * TEXPT, "||": 2.0 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT}

# the centres of the column rules on the print (pt): | thin, ! heavy, || the centre of the double rule between the tables
RULES = [("|", 107.70), ("!", 131.76), ("|", 172.80), ("!", 196.20), ("|", 262.62), ("||", 281.79), ("|", 375.06),
         ("|", 391.68), ("|", 407.70), ("|", 423.12), ("|", 439.50), ("|", 455.88), ("|", 471.54)]
RIGHT = 489.40  # the outer edge of the right frame rule
ALIGN = ["r<", "c", "c", "c", "l>", "c", "l>", "c", "c", "c", "c", "c", "c", "c"]
TEXT_EDGE = {0: ("r", 95.4), 4: ("l", 203.0), 6: ("l", 290.2)}  # where the years end and the months begin (pt)


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    """the edges of the columns (mm from the frame's outer edge), each width rounded to 0.01 mm with the rounding
    carried forward, so that the rules fall where they stand on the print"""
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        a = ALIGN[k]
        if a == "r<":
            a += f"{edges[k][1] - mm(TEXT_EDGE[k][1]):.2f}"
        elif a == "l>":
            a += f"{mm(TEXT_EDGE[k][1]) - edges[k][0]:.2f}"
        toks += [f"{w:.2f}{a}", RULES[k][0] if k < len(RULES) else "||>"]
    return "@cols 0 " + " ".join(toks)


def node(x, y, size, text, rotate=False, anchor="center", font=""):
    rot = ",rotate=90" if rotate else ""
    return (rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) "
            rf"{{\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont{font} {text}}};")


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    seps = [(RULES[k][0], edges[k][1]) for k in range(len(RULES))]  # (kind, left edge mm)
    mid0, mid1 = seps[5][1], seps[5][1] + WIDTH["||"]  # the double rule between the tables
    y_head = ymm(319.72)  # the heavy rule under the heads
    bottom = -y_head + heavy
    L = [r"% Nallino, Part II p. 301: the heads of the tables of the signs of the Arab and of the Persian years and months,",
         r"% drawn to the columns of the body of the tables (generated by figures/src/AB01-PDF0750-F01/head_gen.py;",
         r"% coordinates in mm from the outer edge of the frame and from its top, y upwards)",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});"]
    # the frame: the heavy rule over the tables and the thin one under it (as @rule2), the double rules of its edges
    L.append(rect(0, 0, right, -1.2 * TEXPT))
    L.append(rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT))
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    # the double rule between the tables, from the frame down
    for x in (mid0, mid1 - t):
        L.append(rect(x, -2.6 * TEXPT, x + t, -bottom))
    # the heavy rule under the heads
    L.append(rect(0, y_head, right, y_head - heavy))
    # the left table: the rule under the title; the rule under the heads of the two groups of years
    L.append(rect(WIDTH["<||"], ymm(215.08), mid0, ymm(215.08) - t))
    L.append(rect(WIDTH["<||"], ymm(279.04), edges[3][1], ymm(279.04) - t))
    # its rules: the heavy ones and the one before the signs of the months from the title rule, the thin ones
    # inside the groups of years from the rule under the groups
    for k, top in ((0, 279.04), (1, 215.08), (2, 279.04), (3, 215.08), (4, 215.08)):
        kind, x = seps[k]
        L.append(rect(x, ymm(top), x + WIDTH[kind], y_head))
    # the right table: the rule under its title and the rule under «Ex opere astronomico Maslamae», then its rules
    L.append(rect(mid1, ymm(216.28), right - WIDTH["||>"], ymm(216.28) - t))
    L.append(rect(mid1, ymm(269.52), right - WIDTH["||>"], ymm(269.52) - t))
    for k in range(6, len(seps)):
        kind, x = seps[k]
        L.append(rect(x, ymm(269.52), x + WIDTH[kind], y_head))
    # the texts of the left table
    L.append(node(175.12, 174.40, 13.4, r"\textarabic{جدول علامات العرب}"))
    L.append(node(174.28, 198.50, 12.7, r"Tabula signorum Arabum.", anchor="base", font=r"\bfseries"))
    L.append(node(99.72, 243.16, 10.6, r"\textarabic{المبسوطة}"))
    L.append(node(99.06, 258.96, 10.0, r"[Anni] collecti.", anchor="base"))
    L.append(node(163.88, 243.46, 10.6, r"\textarabic{المجموعة}"))
    L.append(node(164.42, 259.20, 10.0, r"[Anni] singuli.", anchor="base"))
    for x_ar, x_num, x_ann in ((87.84, 87.46, 88.02), (152.72, 152.00, 151.82)):
        L.append(node(x_ar, 291.40, 10.1, r"\textarabic{عدد}"))
        L.append(node(x_num, 305.80, 7.4, r"Numerus", anchor="base"))
        L.append(node(x_ann, 312.20, 7.4, r"[annorum].", anchor="base"))
    for x_ar, x_sig in ((116.14, 127.38), (180.34, 191.76)):
        L.append(node(x_ar, 299.85, 9.2, r"\textarabic{علامات}", rotate=True))
        L.append(node(x_sig, 300.10, 7.8, r"Signa.", rotate=True))
    L.append(node(228.30, 263.38, 10.5, r"\textarabic{الشهور}"))
    L.append(node(229.02, 279.20, 9.3, r"Menses.", anchor="base"))
    L.append(node(271.12, 268.22, 9.9, r"\textarabic{علامات} Signa.", rotate=True))
    # the texts of the right table
    L.append(node(385.72, 174.88, 13.4, r"\textarabic{جدول علامات الفرس}"))
    L.append(node(385.42, 199.80, 12.7, r"Tabula signorum Persarum.", anchor="base", font=r"\bfseries"))
    L.append(node(385.72, 239.20, 11.1, r"\textarabic{من زيج مسلمة}"))
    L.append(node(385.96, 253.90, 9.8, r"Ex opere astronomico Maslamae.", anchor="base"))
    L.append(node(329.20, 285.06, 10.1, r"\textarabic{اسماء الشهور الفارسية}"))
    L.append(node(328.66, 301.00, 9.5, r"Nomina mensium", anchor="base"))
    L.append(node(329.26, 309.70, 9.5, r"Persicorum.", anchor="base"))
    for k in range(7):
        a, b = edges[7 + k]
        L.append(rf"\node[anchor=base] at ({(a + b) / 2:.3f},{ymm(298.70):.3f}) "
                 rf"{{\fontsize{{10.1}}{{12.1}}\selectfont {k + 1}}};")
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0750-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
