"""Generate the head of the table of Nallino, Part II p. 303 (master PDF page 752; the table of the beginnings of the
Coptic years and months, with the intercalation at the end of the year) as a TikZ picture drawn to the columns of the
body of the table, and print the @cols line of the page file. Positions were measured on the print (PDF points,
1/72 in): the rules of the columns (in the middle of the body), the ink of the texts of the head (whose centres the
nodes take) and the baselines of the horizontal lines; the sizes were calibrated on the lengths of the texts.
Writes ../../AB01-PDF0752-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 67.84  # the outer edge of the left frame rule on the print (pt)
Y0 = 142.72  # the top of the heavy rule over the table on the print (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT}

RULES = [("|", x) for x in (104.80, 133.54, 162.22, 191.38, 220.66, 250.30, 279.22, 308.14, 337.30, 366.70, 395.92,
                            424.84, 454.18)]
RIGHT = 490.84  # the outer edge of the right frame rule
ALIGN = ["r<"] + ["c"] * 13
TEXT_EDGE = {0: 93.0}  # where the numbers of the years end (pt)
MONTHS = [  # column, Arabic name and its ink centre, Latin name and its ink centre, the number of days
    (1, "توت", (113.22, 255.46), "Tūt.", (125.40, 255.46), "30"),
    (2, "بابه", (141.66, 255.00), "Bābah.", (154.32, 254.20), "30"),
    (3, "هتور", (172.12, 255.04), "Hatūr.", (183.46, 254.26), "30"),
    (4, "كيهك", (198.84, 252.58), "Kiyahk.", (214.38, 254.74), "30"),
    (5, "طوبه", (228.90, 253.60), "Ṭūbah.", (242.40, 254.20), "30"),
    (6, "امشير", (257.24, 254.98), "Amshīr.", (270.56, 254.44), "30"),
    (7, "برمهوت", (288.46, 255.28), "Barmahūt.", (299.56, 254.62), "30"),
    (8, "برموذه", (317.70, 254.08), "Barmūdhah.", (328.74, 254.14), "30"),
    (9, "بشانس", (345.68, 254.38), "Bashāns.", (358.34, 254.08), "30"),
    (10, "بوونه", (376.28, 254.74), "Bawūnah.", (387.20, 254.56), "30"),
    (11, "ابيب", (404.16, 254.60), "Abīb.", (416.22, 254.56), "30"),
    (12, "مسري", (433.70, 254.50), "Misrī.", (445.76, 254.44), "35"),
]


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        a = ALIGN[k]
        if a == "r<":
            a += f"{edges[k][1] - mm(TEXT_EDGE[k]):.2f}"
        toks += [f"{w:.2f}{a}", RULES[k][0] if k < len(RULES) else "||>"]
    return "@cols 0 " + " ".join(toks)


def node(x, y, size, text, rotate=False, anchor="center", font=""):
    rot = ",rotate=90" if rotate else ""
    return (rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) "
            rf"{{\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont{font} {text}}};")


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    y_title, y_days, y_head = ymm(227.2), ymm(281.08), ymm(306.4)
    bottom = -y_head + heavy
    L = [r"% Nallino, Part II p. 303: the head of the table of the beginnings of the Coptic years and months, drawn to the",
         r"% columns of the body of the table (generated by figures/src/AB01-PDF0752-F01/head_gen.py; coordinates in",
         r"% mm from the outer edge of the frame and from its top, y upwards)",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});",
         rect(0, 0, right, -1.2 * TEXPT), rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT)]
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    L.append(rect(0, y_title, right, y_title - t))
    L.append(rect(0, y_head, right, y_head - heavy))
    L.append(rect(edges[1][0] - t, y_days, edges[12][1] + t, y_days - t))  # the rule over the numbers of days
    for k, (kind, xc) in enumerate(RULES):
        x = edges[k][1]
        L.append(rect(x, y_title - t, x + WIDTH[kind], y_head))
    L.append(node(278.52, 173.24, 13.3, r"\textarabic{جدول لمعرفة رؤس سني القبط ورؤس شهورهم والكبس في اخر السنة}"))
    L.append(node(278.16, 196.70, 12.8, r"Tabula ad cognoscenda initia annorum et mensium Coptorum;", anchor="base",
                  font=r"\bfseries"))
    L.append(node(278.94, 207.50, 12.8, r"et est intercalatio in fine anni.", anchor="base", font=r"\bfseries"))
    L.append(node(81.58, 268.36, 10.2, r"\textarabic{سطر العدد}", rotate=True))
    L.append(node(95.14, 267.40, 9.7, r"Numeri [annorum].", rotate=True))
    for col, ar, (ax, ay), lat, (lx, ly), days in MONTHS:
        a, b = edges[col]
        L.append(node(ax, ay, 10.5, r"\textarabic{" + ar + "}", rotate=True))
        L.append(node(lx, ly, 9.55, lat, rotate=True))
        L.append(rf"\node[anchor=base] at ({(a + b) / 2:.3f},{ymm(296.9):.3f}) "
                 rf"{{\fontsize{{9.9}}{{11.9}}\selectfont {days}}};")
    L.append(node(463.78, 267.82, 10.4, r"\textarabic{الكبائس}", rotate=True))
    L.append(node(477.76, 267.70, 9.7, r"Bisextiles.", rotate=True))
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0752-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
