"""Generate the head of the table of Nallino, Part II p. 306 (master PDF page 755; the conjunctions of the Sun and the
Moon in the collected Arab years) as a TikZ picture drawn to the columns of the body of the table, and print the
@cols line of the page file. Positions were measured on the print (PDF points, 1/72 in). The body has rules only
between the groups of columns; the rules between the columns of a group stand only in the head, under the group
heads. Sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0755-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 116.1  # the outer edge of the left frame rule (pt; the average of the head and the body)
Y0 = 153.0  # the top of the heavy rule over the table (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT, "": 0.0}

# the group rules (|, the average of the head and the body) and the rules that stand only in the head ("")
RULES = [("|", 152.4), ("", 178.38), ("", 203.76), ("|", 231.75), ("", 257.22), ("", 285.18), ("", 308.76),
         ("|", 333.35), ("", 359.34), ("", 386.88), ("", 410.58), ("|", 435.3), ("", 461.70), ("", 489.42),
         ("", 513.00)]
RIGHT = 541.9  # the outer edge of the right frame rule
TEXT_EDGE = [141.0, 170.3, 191.5, 218.5, 251.5, 275.6, 302.6, 326.3, 353.4, 377.5, 404.2, 428.5, 455.2, 479.4, 506.4,
             532.6]  # where the numbers of each column end (pt)
GROUPS = [  # the ordinal, the Arabic name, the Roman numeral, the Latin lines (text, baseline); x centre of each
    (192.14, ("الاول", 259.54), ("ايام الزيادة على التاريخ", 276.52), (191.84, 293.4),
     (("Dies incrementi", 191.90, 302.0), ("supra aeram.", 192.56, 310.6))),
    (282.08, ("الثاني", 258.82), ("وسطي النيرين", 276.10), (282.14, 293.4),
     (("Amborum luminarium", 282.68, 302.0), ("motus medius.", 282.86, 310.6))),
    (384.24, ("الثالث", 263.80), ("خاصة القمر", 280.06), (383.58, 297.2), (("Anomalia Lunae.", 384.60, 305.8),)),
    (485.88, ("الرابع", 267.22), ("حركة العرض", 280.54), (487.08, 297.5), (("Motus latitudinis.", 486.96, 306.2),)),
]
ROMAN = ["I.", "II.", "III.", "IV."]
SUBHEADS = [("Dies.", 165.66), ("Horae.", 190.64), ("Minuta.", 217.80), (None, 244.22), ("Gradus.", 271.84),
            ("Min.", 297.42), ("Sec.", 320.96), (None, 346.36), ("Gradus.", 373.62), ("Min.", 399.50),
            ("Sec.", 422.96), (None, 448.56), ("Gradus.", 475.68), ("Min.", 501.94), ("Sec.", 526.70)]


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        toks.append(f"{w:.2f}r<{edges[k][1] - mm(TEXT_EDGE[k]):.2f}")
        sep = RULES[k][0] if k < len(RULES) else "||>"
        if sep:
            toks.append(sep)
    return "@cols 0 " + " ".join(toks)


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def node(x, y, size, text, anchor="center", rotate=False, bold=False):
    rot = ",rotate=90" if rotate else ""
    f = rf"\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont" + (r"\bfseries" if bold else "")
    return rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) {{{f} {text}}};"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    y_title, y_groups, y_head = ymm(242.64), ymm(321.68), ymm(346.68)
    bottom = -y_head + heavy
    L = [r"% Nallino, Part II p. 306: the head of the table of the conjunctions of the Sun and the Moon in the collected",
         r"% Arab years, drawn to the columns of the body of the table (generated by",
         r"% figures/src/AB01-PDF0755-F01/head_gen.py; coordinates in mm from the outer edge of the frame and from its top,",
         r"% y upwards)",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});",
         rect(0, 0, right, -1.2 * TEXPT), rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT)]
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    L.append(rect(0, y_title, right, y_title - t))
    L.append(rect(0, y_head, right, y_head - heavy))
    L.append(rect(edges[0][1], y_groups, right - WIDTH["||>"], y_groups - t))  # under the group heads
    for k, (kind, xc) in enumerate(RULES):
        if kind == "|":
            x = edges[k][1]
            L.append(rect(x, y_title - t, x + WIDTH["|"], y_head))
        else:
            xm = mm(xc) - WIDTH["|"] / 2
            L.append(rect(xm, y_groups - t, xm + WIDTH["|"], y_head))
    L.append(node(328.98, 188.38, 13.0, r"\textarabic{جدول اجتماعات الشمس والقمر في السنين العربية المجموعة}"))
    L.append(node(328.16, 220.0, 12.85, "Tabula coniunctionum Solis et Lunae in annis Arabicis collectis.",
                  anchor="base", bold=True))
    L.append(node(127.54, 295.60, 11.2, r"\textarabic{السنون العربية المجموعة}", rotate=True))
    L.append(node(138.04, 295.18, 9.8, "Anni Arabici collecti", rotate=True))
    L.append(node(147.34, 295.66, 9.8, "[ab aera].", rotate=True))
    for (xa, (ord_ar, y1), (name_ar, y2), (xr, yr), lat), roman in zip(GROUPS, ROMAN):
        L.append(node(xa, y1, 10.2, r"\textarabic{" + ord_ar + "}"))
        L.append(node(xa, y2, 10.2, r"\textarabic{" + name_ar + "}"))
        L.append(node(xr, yr, 9.7, roman, anchor="base"))
        for text, x, base in lat:
            L.append(node(x, base, 9.7, text, anchor="base"))
    for word, x in SUBHEADS:
        if word:
            L.append(node(x, 336.6, 7.1, word, anchor="base", bold=True))
        else:  # Signa zodiaci., in two lines
            L.append(node(x, 333.0, 7.1, "Signa", anchor="base", bold=True))
            L.append(node(x, 339.4, 7.1, "zodiaci.", anchor="base", bold=True))
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0755-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
