"""Generate the head of the table of Nallino, Part II p. 305 (master PDF page 754; the conversion of the eras by the
single Arab years and months) as a TikZ picture drawn to the columns of the body of the table, and print the @cols
line of the page file. Positions were measured on the print (PDF points, 1/72 in). The picture's bounding box ends
with the heavy rule under the head of the years; the head of the months on the right goes on below it, to its own
heavy rule, beside the first three rows of the years (which leave those columns empty). The body has rules only
between the groups of columns; the thin rules between the columns of the Syrian and the Persian years stand only in
the head (printed broken). Sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0754-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 67.0  # the outer edge of the left frame rule (pt; the average of the head and the body)
Y0 = 138.72  # the top of the heavy rule over the table (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "!": 1.0 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT, "": 0.0}

RULES = [("|", 96.63), ("|", 124.67), ("", 158.10), ("", 190.20), ("", 222.40), ("|", 255.33), ("", 288.70),
         ("", 320.98), ("!", 354.00), ("|", 433.81), ("|", 459.45)]
RIGHT = 489.90  # the outer edge of the right frame rule
# the alignment of each column: right-aligned numbers end at the given x, the years' B and the month names
TEXT = [("r", 87.3), ("c", None), ("r", 147.5), ("r", 179.2), ("r", 211.5), ("r", 243.7), ("r", 278.2), ("r", 310.0),
        ("r", 342.3), ("l", 360.8), ("r", 449.7), ("r", 478.6)]
LEFT_HEAD, MONTHS_HEAD = 285.60, 337.44  # the tops of the heavy rules under the two heads


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        a, x = TEXT[k]
        if a == "r":
            a += f"<{edges[k][1] - mm(x):.2f}"
        elif a == "l":
            a += f">{mm(x) - edges[k][0]:.2f}"
        toks.append(f"{w:.2f}{a}")
        sep = RULES[k][0] if k < len(RULES) else "||>"
        if sep:
            toks.append(sep)
    return "@cols 0 " + " ".join(toks)


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def font(size, bold=False):
    return rf"\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont" + (r"\bfseries" if bold else "")


def node(x, y, size, text, anchor="center", rotate=False, bold=False):
    rot = ",rotate=90" if rotate else ""
    return rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) {{{font(size, bold)} {text}}};"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    y_title, y_groups = ymm(207.40), ymm(264.72)
    y_left, y_months = ymm(LEFT_HEAD), ymm(MONTHS_HEAD)
    bottom = -y_left + heavy
    x_heavy = edges[8][1]  # the heavy rule between the years and the months
    L = [r"% Nallino, Part II p. 305: the head of the table of the conversion of the eras by the single Arab years and",
         r"% months, drawn to the columns of the body of the table (generated by",
         r"% figures/src/AB01-PDF0754-F01/head_gen.py; coordinates in mm from the outer edge of the frame and from its top,",
         r"% y upwards). The bounding box ends with the heavy rule under the head of the years; the head of the months",
         r"% goes on below it.",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\useasboundingbox (0,0) rectangle ({right:.3f},{-bottom:.3f});",
         rect(0, 0, right, -1.2 * TEXPT), rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT)]
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    L.append(rect(0, y_title, right, y_title - t))
    L.append(rect(0, y_left, x_heavy, y_left - heavy))  # under the head of the years
    L.append(rect(x_heavy + WIDTH["!"], y_months, right - WIDTH["||>"], y_months - heavy))  # under the head of the months
    L.append(rect(edges[1][1] + WIDTH["|"], y_groups, x_heavy, y_groups - t))  # under the heads of the two groups
    for k, (kind, xc) in enumerate(RULES):
        x = edges[k][1]
        if kind == "":  # the broken thin rules between the subheads of a group
            xm = mm(xc) - WIDTH["|"] / 2
            L.append(rect(xm, y_groups - t, xm + WIDTH["|"], y_left))
        else:  # the rules of the columns, from the title rule down
            L.append(rect(x, y_title - t, x + WIDTH[kind], -bottom))
    # the title
    L.append(node(278.12, 164.36, 13.8, r"\textarabic{جدول تحويل التواريخ بعضها الى بعض على مبسوطة العرب وشهورهم}"))
    L.append(node(278.90, 186.80, 12.7, "Tabula conversionis aerarum in alias, secundum singulos Arabum annos",
                  anchor="base", bold=True))
    L.append(node(277.64, 197.60, 12.7, "et menses.", anchor="base", bold=True))
    # the heads of the first two columns
    L.append(node(77.88, 247.16, 10.1, r"\textarabic{سنو العرب المبسوطة}", rotate=True))
    L.append(node(90.36, 247.46, 7.45, "Anni Arabum singuli.", rotate=True, bold=True))
    L.append(node(104.76, 246.14, 11.0, r"\textarabic{كبائس العرب}", rotate=True))
    L.append(node(117.48, 247.76, 7.4, "Bisextiles Arabum.", rotate=True, bold=True))
    # the Syrian and the Persian years
    L.append(node(189.18, 225.56, 9.85, r"\textarabic{مبسوطة السريان وهي مكبسة}"))
    L.append(node(189.00, 241.70, 9.8, "Anni singuli Syrorum", anchor="base"))
    L.append(node(189.42, 250.60, 9.8, "cum intercalatione.", anchor="base"))
    L.append(node(304.80, 220.58, 9.85, r"\textarabic{مبسوطة الفرس وهي مطلقة}"))
    L.append(node(304.92, 233.60, 9.85, r"\textarabic{غير مكبسة}"))
    L.append(node(304.86, 250.60, 9.8, "Anni singuli Persarum", anchor="base"))
    L.append(node(304.74, 259.10, 9.8, "sine intercalatione.", anchor="base"))
    for word, x in (("Anni.", 141.72), ("Menses.", 174.18), ("Dies.", 206.52), ("Fract.", 238.08), ("Anni.", 272.40),
                    ("Menses.", 305.28), ("Dies.", 338.04)):
        L.append(node(x, 277.80, 7.2, word, anchor="base", bold=True))
    # the head of the months: Arabic, then the Latin justified with the first line indented, the last line natural
    L.append(node(393.20, 242.42, 10.65, r"\textarabic{شهور العرب تستعمل}"))
    L.append(node(394.40, 258.92, 10.65, r"\textarabic{في جميع التواريخ}"))
    for text, a, b, base, just in (("Menses Arabum,", 364.52, 428.24, 275.5, True),
                                   ("qui [conversioni-", 359.84, 428.36, 284.0, True),
                                   ("bus] omnium ha-", 360.08, 428.12, 292.6, True),
                                   ("rum aerarum in-", 360.32, 427.52, 301.3, True),
                                   ("serviunt.", 359.96, 393.80, 309.7, False)):
        box = rf"\makebox[{(b - a) * BP:.3f}mm][s]{{{text}}}" if just else text
        L.append(rf"\node[anchor=base west] at ({mm(a):.3f},{ymm(base):.3f}) {{{font(9.4)} {box}}};")
    L.append(node(443.18, 274.58, 10.5, r"\textarabic{شهور}", rotate=True))
    L.append(node(454.28, 273.26, 9.8, "Menses [harum aerarum].", rotate=True))
    L.append(node(469.48, 273.38, 10.25, r"\textarabic{ايام}", rotate=True))
    L.append(node(479.26, 273.26, 9.8, "Dies.", rotate=True))
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0754-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
