"""Generate the head of the table of Nallino, Part II p. 307 (master PDF page 756; the oppositions of the Sun and the
Moon in the collected Arab years) as a TikZ picture drawn to the columns of the body of the table, and print the
@cols line of the page file. Positions were measured on the print (PDF points, 1/72 in). The body has rules only
between the groups of columns; the rules between the columns of a group stand only in the head, under the group
heads (moved by SKEW, the shift of the group rules between the head and the middle of the body on the skewed print).
Sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0756-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 61.0  # the outer edge of the left frame rule (pt; the average of the head and the body)
Y0 = 152.64  # the top of the heavy rule over the table (pt)
SKEW = 0.3
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT, "": 0.0}

RULES = [("|", 97.9), ("", 122.76 + SKEW), ("", 148.62 + SKEW), ("|", 176.75), ("", 202.26 + SKEW),
         ("", 229.68 + SKEW), ("", 254.10 + SKEW), ("|", 278.6), ("", 303.84 + SKEW), ("", 332.28 + SKEW),
         ("", 355.92 + SKEW), ("|", 380.7), ("", 405.96 + SKEW), ("", 433.92 + SKEW), ("", 457.62 + SKEW)]
RIGHT = 485.4  # the outer edge of the right frame rule
TEXT_EDGE = [87.2, 115.8, 137.3, 163.2, 197.0, 221.4, 248.1, 272.3, 298.8, 323.3, 349.9, 374.5, 401.3, 425.5, 452.2,
             476.8]  # where the numbers of each column end (pt)
GROUPS = [("I.", 136.36, 275.08, (("Dies incrementi", 136.14, 283.7), ("supra aeram.", 136.86, 292.5))),
          ("II.", 227.16, 275.68, (("Amborum luminarium", 227.62, 284.2), ("motus medius.", 227.92, 292.9))),
          ("III.", 329.44, 280.10, (("Anomalia Lunae.", 329.26, 288.82),)),
          ("IV.", 431.86, 280.34, (("Motus latitudinis.", 431.74, 288.9),))]
SUBHEADS = [("Dies.", 110.70), ("Horae.", 134.64), ("Minuta.", 163.20), (None, 189.50), ("Gradus.", 216.90),
            ("Min.", 242.56), ("Sec.", 266.66), (None, 291.60), ("Gradus.", 318.92), ("Min.", 344.32),
            ("Sec.", 368.44), (None, 393.44), ("Gradus.", 420.84), ("Min.", 446.62), ("Sec.", 470.34)]


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        toks.append(f"{w:.2f}r<{edges[k][1] - mm(TEXT_EDGE[k]):.2f}")
        sep = RULES[k][0] if k < len(RULES) else "||>"
        if sep:
            toks.append(sep)
    return "@cols 0 " + " ".join(toks)


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def node(x, y, size, text, anchor="center", rotate=False, bold=False):
    rot = ",rotate=90" if rotate else ""
    f = rf"\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont" + (r"\bfseries" if bold else "")
    return rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) {{{f} {text}}};"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    y_title, y_groups, y_head = ymm(241.68), ymm(321.12), ymm(345.96)
    bottom = -y_head + heavy
    L = [r"% Nallino, Part II p. 307: the head of the table of the oppositions of the Sun and the Moon in the collected",
         r"% Arab years, drawn to the columns of the body of the table (generated by",
         r"% figures/src/AB01-PDF0756-F01/head_gen.py; coordinates in mm from the outer edge of the frame and from its top,",
         r"% y upwards)",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});",
         rect(0, 0, right, -1.2 * TEXPT), rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT)]
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    L.append(rect(0, y_title, right, y_title - t))
    L.append(rect(0, y_head, right, y_head - heavy))
    L.append(rect(edges[0][1], y_groups, right - WIDTH["||>"], y_groups - t))  # under the group heads
    for k, (kind, xc) in enumerate(RULES):
        if kind == "|":
            x = edges[k][1]
            L.append(rect(x, y_title - t, x + WIDTH["|"], y_head))
        else:
            xm = mm(xc) - WIDTH["|"] / 2
            L.append(rect(xm, y_groups - t, xm + WIDTH["|"], y_head))
    L.append(node(271.46, 187.70, 13.2, r"\textarabic{جدول استقبالات الشمس والقمر في السنين العربية المجموعة}"))
    L.append(node(272.42, 219.4, 12.85, "Tabula oppositionum Solis et Lunae in annis Arabicis collectis.",
                  anchor="base", bold=True))
    L.append(node(75.00, 294.52, 9.75, "Anni Arabum collecti", rotate=True))
    L.append(node(84.42, 294.22, 9.75, "[ab aera].", rotate=True))
    for roman, xr, yr, lat in GROUPS:
        L.append(node(xr, yr, 9.7, roman, anchor="base"))
        for text, x, base in lat:
            L.append(node(x, base, 9.7, text, anchor="base"))
    for word, x in SUBHEADS:
        if word:
            L.append(node(x, 336.0, 7.25, word, anchor="base", bold=True))
        else:  # Signa zodiaci., in two lines
            L.append(node(x, 332.9, 7.25, "Signa", anchor="base", bold=True))
            L.append(node(x, 339.3, 7.25, "zodiaci.", anchor="base", bold=True))
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0756-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
