"""Generate the head of the table of Nallino, Part II p. 300 (master PDF page 749; Maslama's table of the signs of
the beginnings of the Arab years and months) as a TikZ picture drawn to the columns of the body of the table, and
print the @cols line of the page file. Positions were measured on the print (PDF points, 1/72 in): the rules of the
columns, the ink of the texts of the head (whose centres the nodes take) and the baselines of the horizontal Latin
lines; the sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0749-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 120.76  # the outer edge of the left frame rule on the print (pt)
Y0 = 141.72  # the top of the heavy rule over the table on the print (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
RULE, DOUBLE = 0.4 * TEXPT, 2.0 * TEXPT  # the rules of the body: | and || (0.4 pt rules, 1.2 pt apart)

# the centres of the column rules on the print (pt): | single, || the centre of a double rule; the frame
RULES = [("|", 175.78), ("||", 204.88)] + [("|", x) for x in (225.46, 244.6, 264.28, 282.94, 302.26, 321.94, 341.2,
                                                              361.06)] + [("||", 381.31), ("|", 433.06), ("|", 512.74)]
RIGHT = 544.48  # the outer edge of the right frame rule
ALIGN = ["r<{}", "c"] + ["c"] * 9 + ["c", "l>{}", "c"]
YEARS_RIGHT, NOMINA_LEFT = 156.0, 439.4  # where the years end and the names of the months begin (pt)


def mm(x):
    return (x - X0) * BP


def layout():
    """the edges of the columns (mm from the frame's outer edge), each width rounded to 0.01 mm with the rounding
    carried forward, so that the rules fall where they stand on the print"""
    edges, pos = [], DOUBLE
    widths = []
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - (RULE if kind == "|" else DOUBLE) / 2) if xc else mm(RIGHT) - DOUBLE
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + (RULE if kind == "|" else DOUBLE)
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        a = ALIGN[k]
        if a.startswith("r<"):
            a = "r<" + f"{edges[k][1] - mm(YEARS_RIGHT):.2f}"
        elif a.startswith("l>"):
            a = "l>" + f"{mm(NOMINA_LEFT) - edges[k][0]:.2f}"
        toks.append(f"{w:.2f}{a}")
        toks.append(RULES[k][0] if k < len(RULES) else "||>")
    return "@cols 0 " + " ".join(toks)


def node(x, y, size, text, rotate=False, anchor="center", font=""):
    rot = ",rotate=90" if rotate else ""
    return (rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{-(y - Y0) * BP:.3f}) "
            rf"{{\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont{font} {text}}};")


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + DOUBLE  # the outer edge of the right frame
    seps = []  # (kind, left edge mm) of the rules between the columns
    for k in range(len(RULES)):
        seps.append((RULES[k][0], edges[k][1]))
    h_title = (242.0 - Y0) * BP  # the rule under the title
    h_sub = (319.44 - Y0) * BP  # the rule under «Singuli Arabum anni»
    h_head = (346.92 - Y0) * BP  # the heavy rule under the head
    heavy = 1.3 * TEXPT
    bottom = h_head + heavy
    L = []
    L.append(r"% Nallino, Part II p. 300: the head of the table of the signs of the Arab years and months, drawn to the")
    L.append(r"% columns of the body of the table (generated by figures/src/AB01-PDF0749-F01/head_gen.py; coordinates in")
    L.append(r"% mm from the outer edge of the frame and from its top, y upwards)")
    L.append(r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]")
    L.append(rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});")
    # the frame: the heavy rule over the table and the thin one under it (as @rule2), the double rules of its edges
    L.append(rf"\fill (0,0) rectangle ({right:.3f},{-1.2 * TEXPT:.3f});")
    L.append(rf"\fill (0,{-2.2 * TEXPT:.3f}) rectangle ({right:.3f},{-2.6 * TEXPT:.3f});")
    for x in (0, DOUBLE - RULE, right - DOUBLE, right - RULE):
        L.append(rf"\fill ({x:.3f},0) rectangle ({x + RULE:.3f},{-bottom:.3f});")
    # the rule under the title and the heavy rule under the head
    L.append(rf"\fill (0,{-h_title:.3f}) rectangle ({right:.3f},{-h_title - RULE:.3f});")
    L.append(rf"\fill (0,{-h_head:.3f}) rectangle ({right:.3f},{-bottom:.3f});")
    # the rules of the columns: through the head, those inside «Singuli Arabum anni» only under its rule
    for k, (kind, x) in enumerate(seps):
        top = h_sub if 2 <= k <= 9 else h_title
        xs = [x] if kind == "|" else [x, x + DOUBLE - RULE]
        for xx in xs:
            L.append(rf"\fill ({xx:.3f},{-top:.3f}) rectangle ({xx + RULE:.3f},{-h_head:.3f});")
    g0, g1 = edges[2][0], edges[10][1]  # the columns of the single years
    L.append(rf"\fill ({g0:.3f},{-h_sub:.3f}) rectangle ({g1:.3f},{-h_sub - RULE:.3f});")
    # the title
    L.append(node(331.98, 178.50, 13.3, r"\textarabic{جدول استخراج علامات رؤس سني العرب ورؤس شهورهم – من زيج مسلمة}"))
    L.append(node(331.38, 208.48, 12.6, r"Tabula ad invenienda signa initiorum annorum et mensium Arabum.", anchor="base",
                  font=r"\bfseries"))
    L.append(node(331.5, 219.28, 12.6, r"Ex opere astronomico Maslamae.", anchor="base", font=r"\bfseries"))
    # the heads of the columns
    L.append(node(131.46, 296.06, 10.5, r"\textarabic{سنو العرب المجموعة المتفاضلة}", rotate=True))
    L.append(node(147.20, 295.40, 10.5, r"\textarabic{ي ي}", rotate=True))
    L.append(node(158.86, 295.52, 9.7, r"Anni Arabum collecti", rotate=True))
    L.append(node(167.22, 295.46, 9.7, r"[ab aera] per decades.", rotate=True))
    L.append(node(184.86, 294.74, 11.0, r"\textarabic{علامات مجموعة العشرات}", rotate=True))
    L.append(node(198.34, 294.56, 9.7, r"Signa decadum.", rotate=True))
    L.append(node(293.40, 276.10, 10.1, r"\textarabic{سنو العرب المبسوطة}"))
    L.append(node(293.22, 292.04, 9.7, r"Singuli Arabum anni.", anchor="base"))
    for k in range(9):
        a, b = edges[2 + k]
        L.append(rf"\node[anchor=base] at ({(a + b) / 2:.3f},{-(336.0 - Y0) * BP:.3f}) "
                 rf"{{\fontsize{{9.8}}{{11.8}}\selectfont {k + 1}}};")
    L.append(node(399.52, 295.72, 10.1, r"\textarabic{عدد الايام من الشهور}", rotate=True))
    L.append(node(411.46, 294.64, 9.7, r"Numerus dierum", rotate=True))
    L.append(node(421.06, 295.00, 9.7, r"[singulorum] mensium.", rotate=True))
    L.append(node(472.76, 289.88, 10.2, r"\textarabic{اسماء الشهور}"))
    L.append(node(472.60, 305.62, 9.7, r"Nomina mensium.", anchor="base"))
    L.append(node(522.54, 294.04, 9.1, r"\textarabic{علاماتها}", rotate=True))
    L.append(node(536.28, 294.70, 9.7, r"Eorum signa.", rotate=True))
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0749-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
