"""Generate the head of the table of Nallino, Part II p. 302 (master PDF page 751; Maslama's table of the signs of the
Syrian years and months, with the intercalation in December after the Roman method) as a TikZ picture drawn to the
columns of the body of the table, and print the @cols line of the page file. Positions were measured on the print (PDF
points, 1/72 in): the rules of the columns (in the middle of the body; the print is slightly skewed), the ink of the
texts of the head (whose centres the nodes take, or the start of a word on its baseline) and the baselines of the
horizontal Latin lines; the sizes were calibrated on the lengths of the texts. Writes ../../AB01-PDF0751-F01.tex."""
from pathlib import Path

BP = 25.4 / 72  # mm per PDF point
X0 = 116.08  # the outer edge of the left frame rule on the print (pt)
Y0 = 136.68  # the top of the heavy rule over the table on the print (pt)
TEXPT = 25.4 / 72.27  # mm per TeX point
WIDTH = {"|": 0.4 * TEXPT, "<||": 2.0 * TEXPT, "||>": 2.0 * TEXPT}

RULES = [("|", x) for x in (145.36, 169.24, 193.00, 216.52, 251.20, 274.90, 298.72, 322.54, 346.18, 370.06, 393.40,
                            417.46, 440.08, 462.76, 497.44)]
RIGHT = 541.12  # the outer edge of the right frame rule
ALIGN = ["r<"] + ["c"] * 13 + ["r<", "r<"]
TEXT_EDGE = {0: 136.6, 14: 488.6, 15: 529.9}  # where the right-aligned numbers end (pt)
MONTHS = [  # column, the day count, the Arabic name and its ink centre, the Latin name and its ink centre
    (1, "31 dies", (156.50, 222.74), "اكتوبر", (153.62, 273.60), "October.", (164.30, 273.54)),
    (2, "30", (179.96, 222.26), "نونبر", (178.88, 273.84), "November.", (187.70, 273.72)),
    (3, "31", (203.46, 222.68), "دجنبر", (202.38, 274.74), "December.", (211.14, 273.72)),
    (5, "31", (261.24, 222.86), "ينير", (260.82, 274.62), "Ianuarius.", (269.10, 274.14)),
    (6, "28", (284.92, 222.22), "فبرير", (284.10, 273.72), "Februarius.", (292.56, 274.50)),
    (7, "31", (308.50, 222.56), "مارس", (306.10, 274.20), "Martius.", (316.24, 273.84)),
    (8, "30", (332.14, 222.32), "ابريل", (330.34, 274.38), "Aprilis.", (340.66, 273.60)),
    (9, "31", (355.88, 222.68), "مايه", (352.52, 273.72), "Maius.", (363.62, 273.42)),
    (10, "30", (379.54, 222.38), "يونيه", (379.24, 273.66), "Iunius.", (387.28, 274.02)),
    (11, "31", (403.14, 222.98), "يليه", (401.26, 273.78), "Iulius.", (410.82, 274.56)),
    (12, "31", (426.66, 222.86), "اغشت", (423.96, 273.54), "Augustus.", (435.24, 273.66)),
    (13, "30", (450.34, 222.56), "شتنبر", (447.76, 274.44), "September.", (458.74, 273.72)),
]
CELL_WORDS = [  # the Latin of the head of the last two columns: word, start of its ink, baseline (pt)
    ("Columnae", 464.48, 252.8), ("[nume-", 509.68, 252.8), ("rorum]", 470.80, 261.5), ("subtra-", 509.68, 261.5),
    ("hendorum,", 470.80, 270.1), ("[qu", 521.40, 270.1), ("sunt]", 470.80, 278.7), ("multipli", 493.44, 278.7),
    ("28", 525.96, 278.7)]


def mm(x):
    return (x - X0) * BP


def ymm(y):
    return -(y - Y0) * BP


def layout():
    edges, widths, pos = [], [], WIDTH["<||"]
    for kind, xc in RULES + [("||>", None)]:
        target = (mm(xc) - WIDTH[kind] / 2) if xc else mm(RIGHT) - WIDTH["||>"]
        w = round(target - pos, 2)
        widths.append(w)
        edges.append((pos, pos + w))
        pos += w + WIDTH[kind]
    return widths, edges


def cols_line(widths, edges):
    toks = ["<||"]
    for k, w in enumerate(widths):
        a = ALIGN[k]
        if a == "r<":
            a += f"{edges[k][1] - mm(TEXT_EDGE[k]):.2f}"
        toks += [f"{w:.2f}{a}", RULES[k][0] if k < len(RULES) else "||>"]
    return "@cols 0 " + " ".join(toks)


def node(x, y, size, text, rotate=False, anchor="center", font=""):
    rot = ",rotate=90" if rotate else ""
    return (rf"\node[anchor={anchor}{rot}] at ({mm(x):.3f},{ymm(y):.3f}) "
            rf"{{\fontsize{{{size}}}{{{size * 1.2:.1f}}}\selectfont{font} {text}}};")


def rect(x0, y0, x1, y1):
    return rf"\fill ({x0:.3f},{y0:.3f}) rectangle ({x1:.3f},{y1:.3f});"


def main():
    widths, edges = layout()
    print(cols_line(widths, edges))
    right = edges[-1][1] + WIDTH["||>"]
    t = 0.4 * TEXPT
    heavy = 1.3 * TEXPT
    y_title, y_sub, y_head = ymm(201.36), ymm(240.32), ymm(306.0)
    bottom = -y_head + heavy
    L = [r"% Nallino, Part II p. 302: the head of the table of the signs of the Syrian years and months, drawn to the",
         r"% columns of the body of the table (generated by figures/src/AB01-PDF0751-F01/head_gen.py; coordinates in",
         r"% mm from the outer edge of the frame and from its top, y upwards)",
         r"\begin{tikzpicture}[x=1mm,y=1mm,every node/.style={inner sep=0pt,outer sep=0pt}]",
         rf"\path (0,0) rectangle ({right:.3f},{-bottom:.3f});",
         rect(0, 0, right, -1.2 * TEXPT), rect(0, -2.2 * TEXPT, right, -2.6 * TEXPT)]
    for x in (0, WIDTH["<||"] - t, right - WIDTH["||>"], right - t):
        L.append(rect(x, 0, x + t, -bottom))
    L.append(rect(0, y_title, right, y_title - t))
    L.append(rect(0, y_head, right, y_head - heavy))
    for k, (kind, xc) in enumerate(RULES):
        if k == 14:  # the two columns of the numbers to subtract share one head
            continue
        x = edges[k][1]
        L.append(rect(x, y_title - t, x + WIDTH[kind], y_head))
    for col, *_ in MONTHS:  # the rule under the number of days of each month
        a, b = edges[col]
        L.append(rect(a, y_sub, b, y_sub - t))
    # the title
    L.append(node(327.80, 159.98, 13.6, r"\textarabic{جدول علامات السريان على ان الكبس في دجنبر وهو مذهب الروم}"))
    L.append(node(328.34, 181.20, 12.5, r"Tabula signorum Syrorum, intercalatione mense Decembri posita", anchor="base",
                  font=r"\bfseries"))
    L.append(node(327.02, 191.80, 12.5, r"secundum methodum Romanorum.", anchor="base", font=r"\bfseries"))
    # the heads of the columns
    L.append(node(126.74, 254.34, 9.8, r"\textarabic{سطر العدد}", rotate=True))
    L.append(node(139.50, 253.76, 9.55, r"Numerus annorum.", rotate=True))
    L.append(node(227.24, 254.66, 9.8, r"\textarabic{سطر الكبس}", rotate=True))
    L.append(node(241.22, 253.82, 9.55, r"Columna intercalationis.", rotate=True))
    for col, days, (dx, dy), ar, (ax, ay), lat, (lx, ly) in MONTHS:
        L.append(node(dx, dy, 9.6, days, rotate=True))
        L.append(node(ax, ay, 11.0, r"\textarabic{" + ar + "}", rotate=True))
        L.append(node(lx, ly, 7.4, lat, rotate=True, font=r"\bfseries"))
    L.append(node(499.14, 238.44, 10.2, r"\textarabic{سطري المطرّح كح كح}"))
    for word, x, base in CELL_WORDS:
        L.append(rf"\node[anchor=base west] at ({mm(x):.3f},{ymm(base):.3f}) "
                 rf"{{\fontsize{{9.1}}{{10.9}}\selectfont\bfseries {word}}};")
    L.append(r"\end{tikzpicture}")
    out = Path(__file__).resolve().parents[2] / "AB01-PDF0751-F01.tex"
    out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out, f"(height {bottom:.3f} mm)")


if __name__ == "__main__":
    main()
